### ISSUE TITLE
D'n'D for generated elements (polymer)

### ISSUE THREAD

**Issue by pcornelissen** [marcojakob/dart-dnd#10]
Sorry, this isn't an issue per se, but at least this is not a documented usecase ;-)

I have a generated table that is filled by value binding in my polymer component, so rows and cols are data driven.
I want to be able to reorder items that are located in the table columns (and even move them to different columns). Of course the items can and will change over time and as such will be dropped and recreated by polymer.

The initialization of the dnd code seems to be a one time thing. Is there an easy way to attach the existing instance to the new elements? is there a drawback that the associated elements are thrown away from time to time?

**Comment by marcojakob** [comment]
> The initialization of the dnd code seems to be a one time thing. Is there an easy way to attach the existing instance to the new elements?

You should be able to just create new `Draggable`s and pass the newly created elements along. Basically, the `Draggable` constructor just adds some listeners to the elements. 

> is there a drawback that the associated elements are thrown away from time to time?
When you remove elements from the DOM (and don't keep any references around), the listeners should be removed automatically. If you want to remove all listeners from the `Draggable`, you could also call its `destroy()` method.

I'd love to hear how it works out with your polymer components and the dnd library (performence, working with the dnd API, etc.).

**Comment by marcojakob** [comment]
I'm closing this since I haven't heard from anyone else having problems in this area. Feel free to reopen or comment if this is still an issue.
