### ISSUE TITLE
Heavy dependency for the library

### ISSUE THREAD

**Issue by saidatta** [marcojakob/dart-dnd#14]
Hey,

First of all, Good job on the library!
I noticed that polymer dependency is a heavy one. My app is already heavy front-end app that doesn't use polymer.
I am afraid that if I plan to integrate this library that my app will become even more heavier.

1. Thoughts/experiences on the above scenario? 
2. Why did you choose polymer?
3. How heavily embededed is the use of polymer within the library?

Thanks!

**Comment by marcojakob** [comment]
Polymer is only used in an example. It is only a `dev_dependency`.
