### ISSUE TITLE
Angular2 Dart components

### ISSUE THREAD

**Issue by joeblew99** [marcojakob/dart-dnd#16]
The Angular2 Components library went public last week.

https://github.com/dart-lang/angular2_components
 
https://github.com/dart-lang/angular2_components_example

Does anyone know if Drag and Drop can be done with them ? Would be very nice..

**Comment by marcojakob** [comment]
@joeblew99 It would be great. I suspect that the AngularDart UI team might already have a drag and drop solution. Do you want to ask them?

If not, we should test if this dnd library works with them out of the box or if we need to tweak it.

**Comment by joeblew99** [comment]
hey

i asked them: https://github.com/dart-lang/angular2_components/issues/17

Lets see :)
