### ISSUE TITLE
Draggable.destroy should call remove() on avatar

### ISSUE THREAD

**Issue by tomconnell-wf** [marcojakob/dart-dnd#17]
If Draggable.destroy is called while dragging, it will result in the drag avatar sticking around in the location is was at when destroy was called.  It seems like the destroy method should just call remove() on avatarHandler.avatar.

**Comment by marcojakob** [comment]
Would you mind providing a pull request with a fix?

**Comment by tomconnell-wf** [comment]
I think I could make that happen.

**Comment by marcojakob** [comment]
Fixed by #18.
