### ISSUE TITLE
setting Draggable and Dropzone that are built with Future/Stream

### ISSUE THREAD

**Issue by ronmany** [marcojakob/dart-dnd#28]
Hi,

How can I setup Draggable and Dropzone on a list that are made "later" by Stream or Future
I try to instantiate thm in  ngAfterViewInit but it does not help, by the the time I call Draggable or Dropzone the elements are not built yet.

Thank you,

**Comment by marcojakob** [comment]
The way the package is set up currently, you can't add elements to existing `Draggable`s or `Dropzone`s. But maybe you don't need to. Have you tried creating the `Draggable` or `Dropzone` in the ngAfterViewInit?
