### ISSUE TITLE
Dropzones don't work with Shadow DOM due to event retargeting

### ISSUE THREAD

**Issue by friegger** [marcojakob/dart-dnd#3]
The onMouseMove events setup in draggable.dart (https://github.com/marcojakob/dart-dnd/blob/master/lib/src/draggable.dart#L320) will never handle targets within Shadow DOM. Reason for this is, that events from within the Shadow DOM are retargeted to its host. For event handlers setup outside the host, the event target will always be the host and not potential drop targets within.

```
// Install mouseMove listener.
    _dragSubs.add(document.onMouseMove.listen((MouseEvent event) {
```

Also have a look here:
http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-301/#toc-events

A solution might be to also register mouseover handlers, when the dropzone is installed to elements and react properly.

**Comment by marcojakob** [comment]
I've tried to fix this library to work with Shadow DOM. It works like this:

You must add a `dnd-retarget` attribute on all custom where you want events to be forwarded to it's Shadow DOM children. Forwarding happens in `draggable_manager.dart` (https://github.com/marcojakob/dart-dnd/blob/master/lib/src/draggable_manager.dart#L153).

Before I release a new version: Could some of you verify that this works and is a good idea? What do you think about performance?

Here is a live example: http://marcojakob.github.io/dart-dnd/shadow-dom/
And here is the example code: https://github.com/marcojakob/dart-dnd/tree/master/example/shadow-dom

Thanks for all your feedback.

**Comment by marcojakob** [comment]
What do you think @Belsi? Does this fix your problem?

@friegger and @johnryan1982: What do you think about the fix? Is this a good solution (see previous post)? Should I make the new release?

**Comment by marcojakob** [comment]
I'm closing this for now and releasing it in v0.2.0.
