### ISSUE TITLE
Cannot initialize Dropzone with List<HtmlElement>

### ISSUE THREAD

**Issue by frickt** [marcojakob/dart-dnd#30]
Could we change the check in the constructor for Dropzone from:
```
    if (_elementOrElementList is ElementList) {
```
to
```
   if (_elementOrElementList is List<Element>) {
```

I would like to use the library together with angular dart's ViewChildren where i get a List<HtmlElement>.

Or is there a reason for ElementList?

**Comment by marcojakob** [comment]
You are right. That could be allowed. Just released a new version 1.4.1

**Comment by marcojakob** [comment]
@frickt Can you confirm that it works now?

**Comment by frickt** [comment]
wow, that was fast. works perfect. thank you very much!
