### ISSUE TITLE
Clickevent fired when releasing on old position

### ISSUE THREAD

**Issue by zreptil** [marcojakob/dart-dnd#33]
When dragging an element and releasing it in the original place, then the click event of this element is fired. How can i suppress this? The click event is bound to an angular dart element with (click)=",,," so handling the html-element in the dragend-event would not help very much.

**Comment by zreptil** [comment]
When dragging an element and releasing it in the original place, then the click event of this element is fired. How can i suppress this? The click event is bound to an angular dart element with (click) so handling the html-element in the dragend-event would not help very much.

**Comment by marcojakob** [comment]
I think this is by design to allow a click on an element if the user doesn't move or moves just a little. Maybe you could try setting `minDragStartDistance` to `0`.

```
  /// The [minDragStartDistance] is the minimum distance in pixels that is needed
  /// for a drag to start. Default is `4`. This allows for clicks with tiny movement.
```
