### ISSUE TITLE
Pls. add a way to set something like an "invalid-zone" css class

### ISSUE THREAD

**Issue by MikeMitterer** [marcojakob/dart-dnd#7]
First of all - Thanks for your package!
It would be cool if you could add a way to add an indicator for an invalid (not allowed) Drop-Zone.

I tried it with my own Acceptor and it's possible to do something like this:

```dartlang
    @override
    bool accepts(final html.Element draggableElement,final int draggableId,final html.Element dropzoneElement) {

        final bool isValid = _isDragZoneValid();
        if(!isValid) {
            dropzoneElement.classes.add("dnd-invalid");
        } else {
            dropzoneElement.classes.remove("dnd-invalid");
        }
        return isValid;
    }
```

The problem with this approach is that dnd-invalid is set but never unset because an invalid drop-zone never gets onDragLeave... - so no way to remove the dnd-invalid class.

**Comment by marcojakob** [comment]
That's a valid point. I will have a look at that.

**Comment by marcojakob** [comment]
The fix adds a css class (`dnd-invalid` by default) to dropzones when a not-accepted draggable is dragged over.

See it in action: http://marcojakob.github.io/dart-dnd/custom-acceptor/
