### ISSUE TITLE
If the page contents scrolls out of the visible area x + y for mouse position becomes wrong

### ISSUE THREAD

**Issue by MikeMitterer** [marcojakob/dart-dnd#8]
![screenshot-1669](https://cloud.githubusercontent.com/assets/116654/6452195/39b67294-c134-11e4-8c11-cd4af295e6bb.png)

Here you can see where the mouse cursor is and where the draggable object ist.
http://wsk.angular.mikemitterer.at/styleguide/index.html#/draganddrop

The problem becomes even worser on mobile where the page is narrower...

**Comment by MikeMitterer** [comment]
Hmmm I just tried your sample and it works if I scroll the page. You can imagine why it fails in my case?
I have another sample: http://wsk.angular.mikemitterer.at/wsk_dragdrop/index.html
Here it works too. 

The difference is that in the "styleguide-sample" the content is loaded dynamically wether the second sample has only one single page...

**Comment by marcojakob** [comment]
There must be something wrong with the calculations for the absolute positioning of the drag avatar. I've already had a similar issue once when a draggable was inside an element that had an top offset. I wrote a small test example (https://github.com/marcojakob/dart-dnd/tree/master/test/parent-offset).

If you want to take a look:

* The avatar handler takes the `offset.topLeft` to determine the initial position of the draggable element (https://github.com/marcojakob/dart-dnd/blob/master/lib/src/draggable_avatar.dart#L203)
* Then it adds the `marginLeft` and `marginTop` to the offset (https://github.com/marcojakob/dart-dnd/blob/master/lib/src/draggable_avatar.dart#L98).
* Maybe the margin calculations are wrong. See `cacheMargins()` https://github.com/marcojakob/dart-dnd/blob/master/lib/src/draggable_avatar.dart#L116

It would be best if you could provide a small example like the [parent offset test](https://github.com/marcojakob/dart-dnd/tree/master/test/parent-offset) where the scrolling error can be reproduced. Then it shouldn't be too hard to track down the wrong calculations.

**Comment by marcojakob** [comment]
You're using flexbox. Could it be that some calculations get messed up because of the flexbox and scrolling combination?

**Comment by MikeMitterer** [comment]
Hmmm, possible. Thanks. I'll investigate into that. If I know more I'll give your feedback.

**Comment by MikeMitterer** [comment]
It's not flexbox it's a scrollable area. In this sample:
http://wsk.angular.mikemitterer.at/wsk_dragdrop/index.html I've a div (dndcontainer) with height 280px, overflow: scroll. If you soll down x + y start become to be wrong. Maybe you have a solution for this - would be cool!!! 

jQuery had the same problem:
http://stackoverflow.com/questions/5791886/jquery-draggable-shows-helper-in-wrong-place-when-scrolled-down-page
http://stackoverflow.com/questions/28179885/scrolling-messes-up-my-canvas-mouse-coordinates-javascript-telerik-mobile
https://www.google.at/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=overflow+scroll+mouse+y+wrong

**Comment by marcojakob** [comment]
After searching for a long time in the wrong place I found out that this actually isn't a bug (but maybe unexpected behavior). Here is what happens:

The drag avatar has `position: absolute`. Since your scrollable parent is not positioned, the drag avatar is positioned relative to the document.

A simple fix is to use `position: relative` for your scrollable container element. This will correctly position the drag avatar relative to the scrolled container.

I'm currently not sure if and how this should be handled by the `dnd` library. To change this behavior, the `AvatarHandler` would probably need to go through all the non-positioned parents and check if they have been scrolled; then subtract that scrolling amount.

Do you see a better way to handle this?

**Comment by marcojakob** [comment]
I've created a small test example for this issue. The easy fix is to uncomment the `position: relative` of the container in the CSS.
But, it would be nice to provide a better fix. If you want to take a look, here is the line where the `CloneAvatarHandler` sets the initial top-left position of the avatar: https://github.com/marcojakob/dart-dnd/blob/master/lib/src/draggable_avatar.dart#L222

**Comment by marcojakob** [comment]
Hi @MikeMitterer. I've tested your Example on http://wsk.angular.mikemitterer.at/styleguide/index.html#/draganddrop

If you add a `position: relative;` to your `.danddcontainer` the scrolling issue is fixed.

Also, I'd remove the `overflow: scroll;` from the draggable element as they look kind of strange with scroll bars:

![image](https://cloud.githubusercontent.com/assets/2089493/7215271/d2a616ca-e5cf-11e4-9ebe-265c94b01d1f.png)


*Please let me know if you have a better idea to fix the scrolling issue from inside the dnd library.*

**Comment by MikeMitterer** [comment]
I never said "Thank you" - late but (hopefully) better then never: :sparkles::sparkles: "Thank you" :sparkles::sparkles: I'm using your package in my upcoming MaterialDesignLite/Dart library and with position: relative; it works just fine!
