### ISSUE TITLE
NoSuchMethodError: method not found: 'pubspec'

### ISSUE THREAD

**Issue by MikeMitterer** [marcojakob/dart-dnd#9]
Since 0.2.0 I get 
```
Precompiling dependencies...
Loading source assets...
The null object does not have a getter 'pubspec'.

NoSuchMethodError: method not found: 'pubspec'
Receiver: null
Arguments: []
dart:core                                                                                                                       Object.noSuchMethod
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 251   _PackageDependencyComputer._PackageDependencyComputer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 199   DependencyComputer._loadPackageComputer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 107   DependencyComputer._transformersNeededByTransformer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 258   _PackageDependencyComputer._PackageDependencyComputer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 199   _loadPackageComputer
dart:core                                                                                                                       List.forEach
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 53    DependencyComputer.DependencyComputer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/load_all_transformers.dart 33  loadAllTransformers.<async>
dart:isolate
```

If I remove the dependency to your package the error is gone.

**Comment by MikeMitterer** [comment]
Hmm, maybe it's your dev_dependencies. You are referencing polymer in dev_dependencies but you are using the polymer transformer in your "regular" dependencies. I think this leads to problems at my end because it can't find the polymer-transformers. 

Using one pubspec.yaml for your samples and the main package results into such problems.
Because of this all my samples get their own .yaml and their own web-dir.
https://github.com/MikeMitterer/dart-wsk-material/tree/master/example

I took this approach from angulardart - they use the same structure. Its a bit more work but it makes your samples really "independent" of your main package

**Comment by marcojakob** [comment]
I was just investigating on the same track. Thank you for the hint.

**Comment by marcojakob** [comment]
I'm trying your approach, @MikeMitterer, with creating a separate `pubspec.yaml` file for every example. It seems to work but I still had to add all the dependencies needed in examples as *dev_dependencies* to the main `pubspec.yaml`. Otherwise, the DartEditor would complain.

**Comment by marcojakob** [comment]
So, finally got everything working again with continous deployment on drone.io. I had to specifically go to the subfolder of the example with Shadow DOM and build it seperately. Otherwise, the polymer transformer would not get picked up.
https://github.com/marcojakob/dart-dnd/blob/master/tool/drone_io.sh

Version 0.2.1 contains the fix. Thank you for helping out @MikeMitterer

**Comment by MikeMitterer** [comment]
Sure, thank you too!
